version: "3"

# ShadowTrace Docker Compose Configuration
#
# Basic usage:
#     $ docker-compose up --build
#
# Open browser at http://localhost:5001

services:
  shadowtrace:
    build:
      context: ./
    image: shadowtrace
    container_name: shadowtrace
    ports:
      - "5001:5001"
    restart: unless-stopped
