#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f shadowtrace.key; then
  echo "Error: shadowtrace.key already exists"
  exit 1
fi

if test -f shadowtrace.crt; then
  echo "Error: shadowtrace.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out shadowtrace.crt -keyout shadowtrace.key -subj "/CN=localhost"

chmod 600 shadowtrace.crt
chmod 600 shadowtrace.key
